name: Laravel CI & 🚀 Deploy

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master ]

jobs:
  # ==========================
  #  Laravel Continuous Integration (SQLite)
  # ==========================
  build:
    name: 🧪 Laravel CI (SQLite)
    runs-on: ubuntu-22.04

    env:
      DB_CONNECTION: sqlite
      DB_DATABASE: database/database.sqlite

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, bcmath, gd, pdo_sqlite
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Prepare environment
        run: |
          cp .env.example .env
          php artisan key:generate
          mkdir -p database
          touch database/database.sqlite
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=${{ github.workspace }}/database/database.sqlite" >> .env

      - name: Run migrations
        run: php artisan migrate --force

  # ==========================
  #  Deployment Job
  # ==========================
  deploy:
    name: 🚀 Deploy (Git Pull Only)
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
          ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'ENDSSH'
          set -e
          cd ${{ secrets.DEPLOY_PATH }}
          git fetch origin main
          git reset --hard origin/main
          git clean -fd
          echo "✅ Deployment completed successfully"
          ENDSSH
